<?php if (Orion_Auth::isLogged() == null): ?>
    <div id="login_box">
        <div class="top_info">
            <span class="top"><?=$this->translate('ADMIN_ACCOUNT_RESET_PASSWORD')?></span>
        </div>
        <?=$this->form?>
        <div class="both"></div>
        <a class="remind_password" href="<?=$this->url(array(),'admin-auth-login')?>"><?=$this->translate('ADMIN_ACCOUNT_LOGIN')?></a>
        <div class="bottom_info">
            <?=$this->translate('APPLICATION_VERSION');?> <span class="top"><?=$this->app_version;?></span>
        </div>
    </div>
<?php endif; ?>
