<?php
class App_Form_Admin_Attributes extends App_Form_Base
{  
    public function init()
    {
        $this->setName('Groups');
        $this->addAttribs(array('class' => 'form-horizontal'));
        
        $name = new Zend_Form_Element_Text('name');
        $name->setRequired(true)
                 ->setLabel('FORMS_NAME')
                 ->setDecorators($this->textDecorator)->getDecorator('Label')->setRequiredSuffix(self::REQUIRED_FIELD);
        
        $status = new Zend_Form_Element_Checkbox('status');
        $status ->setLabel('FORMS_STATUS_ACTIVE')
                 ->setDecorators($this->textDecorator);
        
        $not_required = new Zend_Form_Element_Checkbox('not_required');
        $not_required ->setLabel('FORMS_STATUS_NOT_REQUIRED')
                 ->setDecorators($this->textDecorator);
        
        $group_id = new Zend_Form_Element_Select('group_id');
        $group_id->setRequired(true)
                 ->setLabel('FORMS_GROUP_ID')
                ->setMultiOptions($this->getGroups())
                 ->setDecorators($this->selectDecorator)->getDecorator('Label')->setRequiredSuffix(self::REQUIRED_FIELD);
                 
        $step = new Zend_Form_Element_Text('step');
        $step->setRequired(true)
                 ->setLabel('FORMS_STEP')
                ->addValidator(new Zend_Validate_Float())
                 ->setDecorators($this->textDecorator)->getDecorator('Label')->setRequiredSuffix(self::REQUIRED_FIELD);

        $type = new Zend_Form_Element_Select('type');
        $type->setRequired(true)
            ->setLabel('FORMS_TYPE')
            ->setMultiOptions([App_Model_Anastomosis_DbTable::TYPE_INPUT_TEXT => 'Input', App_Model_Anastomosis_DbTable::TYPE_INPUT_SELECT => 'Select'])
            ->setDecorators($this->selectDecorator)->getDecorator('Label')->setRequiredSuffix(self::REQUIRED_FIELD);

        $submit = new Zend_Form_Element_Submit('submit');
        $submit->setIgnore(true)
            ->setAttrib('class','btn')
            ->setDecorators($this->submitDecorator)
            ->setLabel('FORMS_SAVE');

        $min = new Zend_Form_Element_Text('min');
        $min->setRequired(true)
            ->setLabel('FORMS_MIN')
            ->setDecorators($this->selectDecorator)->getDecorator('Label')->setRequiredSuffix(self::REQUIRED_FIELD);


        $max = new Zend_Form_Element_Text('max');
        $max->setRequired(true)
            ->setLabel('FORMS_MAX')
            ->setDecorators($this->selectDecorator)->getDecorator('Label')->setRequiredSuffix(self::REQUIRED_FIELD);


               
        $this->addElements(array(
            $name,
            $status,
            $group_id,
            $step,
            $not_required,
            $type,
            $min,
            $max,
            $submit
        ));
    }
    
    public function getGroups()
    {
        $model = new App_Model_Groups_DbTable();
        return $model->getActiveToForm();
    }

    public function isValid($data)
    {
        $validatorGreaterThan = new Zend_Validate_GreaterThan(array('min' => $data['min']));
        $this->getElement('max')->addValidator($validatorGreaterThan);
        $validatorGreaterThan = new Zend_Validate_LessThan(array('max' => $data['max']));
        $this->getElement('min')->addValidator($validatorGreaterThan);


        return parent::isValid($data); // TODO: Change the autogenerated stub
    }
}