<table id="navi">
    <tbody>
        <tr>
            <td>
                <a href="<?=$this->url(array(),'admin-configuration-global')?>">
                    <img alt="<?=$this->translate('ADMIN_CONFIGURATION_GLOABAL') ?>"  title="<?=$this->translate('ADMIN_CONFIGURATION_GLOABAL') ?>" src="<?=$this->imagePath('ikons/configuration_global.jpg',false,'admin')?>" />
                    <br />
                    <?=$this->translate('ADMIN_CONFIGURATION_GLOABAL') ?>
                </a>
            </td>
            <td>
                <a href="<?=$this->url(array(),'admin-configuration-smtp')?>">
                    <img alt="<?=$this->translate('ADMIN_CONFIGURATION_SMTP') ?>"  title="<?=$this->translate('ADMIN_CONFIGURATION_SMTP') ?>" src="<?=$this->imagePath('ikons/configuration_smtp.jpg',false,'admin')?>" />
                    <br />
                    <?=$this->translate('ADMIN_CONFIGURATION_SMTP') ?>
                </a>
            </td>
        </tr>
    </tbody>
</table>