<img src="cid:logo"/> <br />
<h2 style="margin: 0 0 0 15px;color: #055BA3; text-transform: uppercase; width: 300px; float:left">Pokoje-do-wynajęcia.pl - Aktywacja konta</h2>
<div style="clear:both" ></div>
<hr />
Aby aktywować konto kliknij w poniższy link: <br/><br/> <a href="<?=$this->mailUrl.$this->url(array('code' => $this->code),'site-activation')?>"><?=$this->mailUrl.$this->url(array('code' => $this->code),'site-activation')?></a>
<hr />
Pozdrawiamy,<br/>
Zespół <span>pokoje-do-wynajęcia</span>