<img src="cid:logo"/> <br />
<div style="float:left"><img src="cid:ico" src="float:left;"/></div><h2 style="margin: 0 0 0 15px;color: #055BA3; text-transform: uppercase; width: 300px; float:left">Resetowanie hasła</h2>
<div style="clear:both" ></div>
<hr />
Aby zresetować haslo kliknij w link <a href="<?=$this->mailUrl.$this->url(array('code'=>$this->key_reminder),'site-auth-reset-password')?>">Zresetuj hasło</a>
<hr />
Radyjko.net