<?=$this->headTitle()->setSeparator(' - ')->headTitle($this->title)
        ->headTitle($this->translate('PRESS GLASS - System deklaracji'),'APPEND'); ?>
<?=$this->headMeta()->setName('robots', 'NOINDEX, NOFOLLOW');?>
<?=$this->headLink()->prependStylesheet($this->baseUrl().'/skin/global/css/all.css')
                    ->prependStylesheet($this->baseUrl().'/skin/admin/css/all.css')
                    ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/gif',
                                     'href' => $this->baseUrl('favicon.ico')));
?> 
<?=$this->headStyle(); ?>
<?=$this->headScript()->prependFile($this->baseUrl().'/skin/global/js/jquery-1.8.2.min.js')
                      ->appendFile($this->baseUrl().'/skin/global/js/jquery.jclock.js')
                      ->appendFile($this->baseUrl().'/skin/global/js/bootstrap.js')
                      ->appendFile($this->baseUrl().'/skin/global/js/jquery-ui-1.9.1.custom.min.js')
                      ->appendFile($this->baseUrl().'/skin/global/js/jquery.cookie.js')
                      ->appendFile($this->baseUrl().'/skin/global/js/sitemapstyler.js')
                      ->appendFile($this->baseUrl().'/skin/global/js/jquery.tipsy.js')
                      ->appendFile($this->baseUrl().'/skin/admin/js/tiny_mce/tiny_mce.js');
?>                                                                      
<script type="text/javascript">
$(function(){
    $('a').tipsy({
        live: true,
        delayIn: 300
    });
    $( ".datePicker" ).datepicker({
        showOn: "button",
        buttonText: "<i class='icon-calendar icon-black'></i>",
        dateFormat: "yy-mm-dd"
    }).next(".ui-datepicker-trigger").addClass("btn");
    $('#jclock').jclock();
});
$(document).ready(function(){
    $('.label').each(function(){
       $(this).removeClass('label');
    });
    var i =0 ;
    $("div.header_right").each(function () {
        i++;
        if($.cookie('link_'+i) == 1){
            $('#link_'+i).parent().parent().next().hide();
            $('#link_'+i).toggleClass('icon_active', 'icon_nonactive');
       } 
    });
    $('.link').mouseover(function(){
        $(this).children('a.litle').show();    
    });
    $('.link').mouseout(function(){
        $(this).children('a.litle').hide();    
    });
    $('.icon_nonactive').click(function(){
        $(this).toggleClass('icon_active', 'icon_nonactive');
        var id = $(this).attr('id');
        if($(this).is('.icon_active')){
            $.cookie(id, '1');
        } else {
            $.cookie(id, '0'); 
        }
        $(this).parent().parent().next().slideToggle("slow");
    });      
});
/* AJAX DATEPICKER */

$('.ui-state-default').live('click', function(){
    
    var name = $('.datepicker').attr('name');
    $('.datepicker').next('ul.errors').remove();
    var input = $('.datepicker');
    var action =  $('.datepicker').parent().parent().parent('form').attr('action');
    var value = $('.datepicker').val();
    var data = new Object;
    data[name] = value; 
    var html ;
    $.ajax({
        type: "POST",
        url: action,
        data: data,
        success: function(msg)
        {  
            if(msg != 'ok')
            {   
                $
                html = '<ul id="errors_'+name+'"class="errors">'
                for(e in msg[name])
                {
                    html +='<li>'+msg[name][e]+'</li>';
                }
                html += '</ul>'
               $(input).after(html);
            }
        }
     }); 
});
/* FLASHMESSAGE */
$('#x_infos, #close_infos').live('click', function(){
  $(this).parent().animate({
    opacity: 0.25,
    bottom: '+=50',
    height: 'toggle'
  }, 500, function() {
  });
});
tinyMCE.init({
        // General options
        mode : "textareas",
        editor_selector : "mceEditor",
        theme : "advanced",
        plugins : "jbimages,autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",
        language : "pl",
        width : "910",
        height: "620",
        // Theme options
        relative_urls : false,
        theme_advanced_buttons1 : "jbimages,|save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        skin : "o2k7",
        skin_variant : "silver",
        // Style formats
        style_formats : [
                {title : 'Bold text', inline : 'b'},
                {title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
                {title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
                {title : 'Example 1', inline : 'span', classes : 'example1'},
                {title : 'Example 2', inline : 'span', classes : 'example2'},
                {title : 'Table styles'},
                {title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
        ],

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        }
});
</script>