<form id="forms" style="padding-top: 20px;" action="<?=$this->url(array('lang' => $this->lang),'site-pdf')?>" method="POST">
    <label style="position: relative;
top: -10px;
left: 72px;"><input type="checkbox" id="disable_rw" name="disable_rw" value="1"><?=$this->translate('SITE_DISABLE')?> Rw</label>
    <label  style="position: relative;
top: -10px;
left: 198px;"><input checked="checked" name="disable_param" value="1" type="checkbox" id="disable_param"><?=$this->translate('SITE_USE_PARAMS')?></label>
    <div class="radio" style="overflow: hidden;"> 
        <label style="float: right; margin-right: 66px;"><input checked="checked"  type="radio" value="2" name="options">[R<sub>A</sub>;R<sub>Atr</sub>]</label>
        <label style="float: right; margin-right: 112px;" ><input  type="radio" value="1" name="options">[C;C<sub>tr</sub>]</label>
    </div>
    <?php $i=1; foreach($this->group as $group_name =>  $sliders):?>
        <?php $array_keys = array_keys($sliders);?>
        <?php $elem =($sliders[array_shift($array_keys)]->toArray());?>
        <div class="element <?=($i != 1 && $elem['can_hide'] == 1) ? 'hide' : '';?> <?=($i != 1) ? 'disabled' : '';?>">
            <?Php $right = (532/(count($sliders)+1)-50);?>
            <div class="item" style='margin-right: <?=$right?>px; position:relative;'>
                <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px; height: 27px;"><?=$elem['group_name']?></p>
                <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px; height: 27px; position: absolute;bottom: 18px;left: 14px;"><?=$elem['hint']?></p>
            </div>
            <?php foreach($sliders as $value):?>
            <?php 
             $val = $value->min_value;
             
             if($value->id == 12 ){
                 $s1 = $sliders[10]->toArray();
                 $s2 = $sliders[14]->toArray();
                 $val = $s2['min_value'] - $s1['min_value'];
             }
             if($value->id == 13 ){
                 $s1 = $sliders[10]->toArray();
                 $s2 = $sliders[15]->toArray();
                 $val = $s2['min_value'] - $s1['min_value'];
             }
            ?>
                <div class="item" style='margin-right: <?=$right?>px;'>
                    <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; "><?=$value->name?></p>
                    <a class="up" href="#"><img src="<?=$this->imagePath('arrow_up.png')?>" /></a>
                    <div id="slider_item_<?=$value->id?>" class="slider-vertical" style="height:200px;"></div>
                    <a class="down" href="#"><img src="<?=$this->imagePath('arrow_down.png')?>" /></a>
                    <input   name="<?=$value->id?>" type="text" value="<?=$val?>" class="slider_amount" />
                </div>
                <script>
                    $(function() {
                        $( "#slider_item_<?=$value->id?>" ).slider({
                                orientation: "vertical",
                                range: "min",
                                min: parseInt('<?=(empty($value->min_value) || !in_array($value->id, array('10','12','13'))) ? $value->min_value : $value->min_value ?>'),
                                max: parseInt('<?=(empty($value->max_value) || !in_array($value->id, array('10','12','13'))) ? $value->max_value : $value->max_value ?>'),
                                step: parseFloat('<?=preg_replace('/,/', '.', $value->step)?>'),
                                value: parseInt('<?=$val?>'),
                                slide: function( event, ui ) {
                                    $(ui.handle).parent().parent().find('.slider_amount').val( ui.value );
                                },
                                change: function( event, ui ) {
                                    $(ui.handle).parent().parent().find('.slider_amount').val( ui.value );
                                    <?php if($value->id == 10):?>
                                        if($('#disable_rw').is(':checked') == false){
                                            s_value1 = $('#slider_item_12').slider( "value" );
                                            if($('#slider_item_14').next().next().val() != s_value1+ui.value){
                                                $('#slider_item_14').next().next().val(s_value1+ui.value).trigger('change');
                                            }
                                            s_value2 = $('#slider_item_13').slider( "value" );
                                            if($('#slider_item_15').next().next().val() != s_value2+ui.value){
                                                $('#slider_item_15').next().next().val(s_value2+ui.value).trigger('change');
                                            }
                                        }
                                    <?php endif;?>
                                    <?php if($value->id == 12 ):?>
                                        s_value1 = $('#slider_item_10').slider( "value" );
                                        if($('input[name="options"]:checked').val() == 2){
                                            c_max_value = $('#slider_item_12').slider( "option", "max" );
                                            c_min_value = $('#slider_item_12').slider( "option", "min" );
                                            if(ui.value == c_max_value || ui.value == c_min_value){
                                                $('#disable_rw').click();
                                            }    
                                        }
                                        if($('#disable_rw').is(':checked') == false){
                                            s_value1 = $('#slider_item_10').slider( "value" );
                                            if($('#slider_item_14').next().next().val() != s_value1+ui.value){
                                                $('#slider_item_14').next().next().val(s_value1+ui.value).trigger('change');
                                            }
                                        }
                                    <?php endif;?>
                                    <?php if($value->id == 13 ):?>
                                        s_value1 = $('#slider_item_10').slider( "value" );
                                        if($('input[name="options"]:checked').val() == 2){
                                            c_max_value = $('#slider_item_13').slider( "option", "max" );
                                            c_min_value = $('#slider_item_13').slider( "option", "min" );
                                            if(ui.value == c_max_value || ui.value == c_min_value){
                                                $('#disable_rw').click();
                                            }    
                                        }
                                        if($('#disable_rw').is(':checked') == false){
                                            s_value1 = $('#slider_item_10').slider( "value" );
                                            if($('#slider_item_15').next().next().val() != s_value1+ui.value){
                                                $('#slider_item_15').next().next().val(s_value1+ui.value).trigger('change');
                                            }
                                        }
                                    <?php endif;?>
                                    <?php if($value->id == 14 ):?>
                                        if($('#disable_rw').is(':checked') == false){
                                            s_value1 = $('#slider_item_10').slider( "value" );
                                            min_value = $('#slider_item_12').slider( "option", "min" );
                                            value = $('#slider_item_12').slider( "value" );
                                            if(min_value+s_value1 > ui.value){
                                                $('#slider_item_12').next().next().val($('#slider_item_12').slider( "option", "min" ) ).change();
                                            } else if($('#slider_item_12').next().next().val() != ui.value - s_value1){
                                                $('#slider_item_12').next().next().val(ui.value - s_value1).trigger('change');
                                            }
                                        } 
                                    <?php endif;?>
                                    <?php if($value->id == 15 ):?>
                                            if($('#disable_rw').is(':checked') == false){
                                                s_value1 = $('#slider_item_10').slider( "value" );
                                                min_value = $('#slider_item_13').slider( "option", "min" );
                                                value = $('#slider_item_10').slider( "value" );
                                                if(min_value+s_value1 > ui.value){
                                                    $('#slider_item_13').next().next().val($('#slider_item_13').slider( "option", "min" ) ).change();
                                                }else if($('#slider_item_13').next().next().val() != ui.value - s_value1){
                                                    $('#slider_item_13').next().next().val(ui.value - s_value1).trigger('change');
                                                }
                                            }
                                    <?php endif;?>
                                    <?php if(!in_array($value->id, array(10,12,13,14,15))):?>
                                        $('#slider_item_10').next().next().trigger('change');
                                    <?php endif;?>
                                }
                        });
                    });
                </script>
            <?php endforeach;?>
            <?php if($i == 1 && count($this->group) > 1):?>
                <label style="float:left; position: relative; top: 40px;"><input name="disable_band" value="1" type="checkbox" id="disable_band"><?=$this->translate('SITE_USE_BAND')?></label>
                <a id="terc"  class="btn-slider" href="#" style="float:right; position: relative; top: 40px; right: 26px;"><?=$this->translate('SITE_SHOW_TERC')?></a>
            <?php endif;?>
        </div>
    <?php $i++; endforeach; ?>
    <input class="btn-slider" id="submit_print" type="submit" value="<?=$this->translate('SITE_SAVE')?>" />
</form>
<script>
$(function() {
    $('#disable_rw').click(function(){
       if($('#disable_param').is(':checked') == false){
            if($('input[name="options"]:checked').val() == 1){
                if($(this).is(':checked') == true){
                    return false;
                }
            }
       }
       if($(this).is(':checked')){
            $('#slider_item_10').slider( "option", "disabled", true );
            $('#slider_item_10').next().next().attr('disabled', true);
       } else {
           $('#slider_item_10').slider( "option", "disabled", false );
           $('#slider_item_10').next().next().attr('disabled', false);
       }
       $('#slider_item_10').next().next().trigger('change');
    });
    $('#block').height($(document).height());
    $('#terc').click(function(e){
        e.preventDefault();
        $('.hide').toggle(); 
        $('.element').toggleClass('bg');
    });
    // BAND
    $('#disable_band').click(function(e){
        disabled = ($('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled"));
        if(disabled == false){
            $('.disabled').find('.slider_amount').attr('disabled', true);
            $('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled", true );
        } else {
            $('.disabled').find('.slider_amount').attr('disabled', false);
            $('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled", false );   
        }
        $('#slider_item_10').next().next().trigger('change');
    });
    
    disabled = ($('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled"));
    if(disabled == false){
        $('.disabled').find('.slider_amount').attr('disabled', true);
        $('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled", true );
    } else {
        $('.disabled').find('.slider_amount').attr('disabled', false);
        $('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled", false );   
    }
    //END BAND
    
    // START PARAM
    $('#disable_param').click(function(){
        disabled = $(this).is(':checked');
        if(disabled == true){
            $('.radio').next().find('.slider_amount').each(function(){
                if($(this).attr('name') != 10){
                    $(this).attr('disabled', true);  
                    $(this).prev().prev().slider( "option", "disabled", true );
                }
            });
        } else {
            $('.radio').next().find('.slider_amount').each(function(){
                if($(this).attr('name') != 10){
                    $(this).attr('disabled', false);  
                    $(this).prev().prev().slider( "option", "disabled", false );
                }
            });
            if($('input[name="options"]:checked').val() == 2){
                $('#slider_item_12').slider( "option", "disabled", true );
                $('#slider_item_12').next().next().attr('readonly', true);
                $('#slider_item_13').slider( "option", "disabled", true );
                $('#slider_item_13').next().next().attr('readonly', true);
            } else {
                $('#disable_rw').click();
                $('#slider_item_14').slider( "option", "disabled", true );
                $('#slider_item_14').next().next().attr('readonly', true);
                $('#slider_item_15').slider( "option", "disabled", true );
                $('#slider_item_15').next().next().attr('readonly', true);
            }
        }
        $('#slider_item_10').next().next().trigger('change');
    });
    disabled = $('#disable_param').is(':checked');
    if(disabled == true){
        $('.radio').next().find('.slider_amount').each(function(){
            if($(this).attr('name') != 10){
                $(this).attr('disabled', true);  
                $(this).prev().prev().slider( "option", "disabled", true );
            }
        });
    } else {
        $('.radio').next().find('.slider_amount').each(function(){
            if($(this).attr('name') != 10){
                $(this).attr('disabled', false);  
                $(this).prev().prev().slider( "option", "disabled", false );
            }
        });
        if($('input[name="options"]:checked').val() == 2){
            $('#slider_item_12').slider( "option", "disabled", true );
            $('#slider_item_12').next().next().attr('readonly', true);
            $('#slider_item_13').slider( "option", "disabled", true );
            $('#slider_item_13').next().next().attr('readonly', true);
        } else {
            $('#slider_item_14').slider( "option", "disabled", true );
            $('#slider_item_14').next().next().attr('readonly', true);
            $('#slider_item_15').slider( "option", "disabled", true );
            $('#slider_item_15').next().next().attr('readonly', true);
        }
    }
    //END PARAM
    $('.up').click(function(e){
        e.preventDefault();
        var value = $( this ).next().slider( "value" );
        if($( this ).next().slider( "option", "disabled"  ) == true){
            return false;
        }
        $( this ).next().slider( "value", value+1 );
    });
    $('.down').click(function(e){
        e.preventDefault();
        var value = $( this ).prev().slider( "value" );
        if($( this ).prev().slider( "option", "disabled"  ) == true){
            return false;
        }
        $( this ).prev().slider( "value", value-1 );
    });
    $('input[name="options"]').click(function(){
        if($('#disable_param').is(':checked') == true){
            return false;
        }
       if($(this).val() == 2){
           $('#slider_item_12').slider( "option", "disabled", true );
           $('#slider_item_12').next().next().attr('readonly', true);
           $('#slider_item_13').slider( "option", "disabled", true );
           $('#slider_item_13').next().next().attr('readonly', true);
           
           $('#slider_item_14').slider( "option", "disabled", false );
           $('#slider_item_14').next().next().attr('readonly', false);
           $('#slider_item_15').slider( "option", "disabled", false );
           $('#slider_item_15').next().next().attr('readonly', false);
       } else {
           if($('#disable_rw').is(':checked') == true){
                $('#disable_rw').click();
           }
           $('#slider_item_12').slider( "option", "disabled", false );
           $('#slider_item_12').next().next().attr('readonly', false);
           $('#slider_item_13').slider( "option", "disabled", false );
           $('#slider_item_13').next().next().attr('readonly', false);
           
           $('#slider_item_14').slider( "option", "disabled", true );
           $('#slider_item_14').next().next().attr('readonly', true);
           $('#slider_item_15').slider( "option", "disabled", true );
           $('#slider_item_15').next().next().attr('readonly', true);
       }
    }).first().click();
    
    function setValue(element, val){
        if($('#disable_rw').is(':checked') == true){
            id = $(element).prev().prev().attr('id');
            if(id != 'slider_item_10' && id != 'slider_item_12' && id != 'slider_item_13'  ){
                $(element).prev().prev().slider( "option", "disabled", false  );
                $(element).prev().prev().slider( "value", val);
            }
        } else {
            $(element ).prev().prev().slider( "option", "disabled", false  );
            $( element ).prev().prev().slider( "value", val);
        }
    }
    $('.slider_amount').change(function(){
         val = $('input[name="options"]:checked').val();
         setValue($(this),$(this).val());
         if($('#disable_rw').is(':checked') == true){
              $('#slider_item_10').slider( "option", "disabled", true );
              $('#slider_item_10').next().next().attr('readonly', true);
         }
        if(val == 2){
           $('#slider_item_12').slider( "option", "disabled", true );
           $('#slider_item_12').next().next().attr('readonly', true);
           $('#slider_item_13').slider( "option", "disabled", true );
           $('#slider_item_13').next().next().attr('readonly', true);

           $('#slider_item_14').slider( "option", "disabled", false );
           $('#slider_item_14').next().next().attr('readonly', false);
           $('#slider_item_15').slider( "option", "disabled", false );
           $('#slider_item_15').next().next().attr('readonly', false);
       } else {
           $('#slider_item_12').slider( "option", "disabled", false );
           $('#slider_item_12').next().next().attr('readonly', false);
           $('#slider_item_13').slider( "option", "disabled", false );
           $('#slider_item_13').next().next().attr('readonly', false);

           $('#slider_item_14').slider( "option", "disabled", true );
           $('#slider_item_14').next().next().attr('readonly', true);
           $('#slider_item_15').slider( "option", "disabled", true );
           $('#slider_item_15').next().next().attr('readonly', true);
       }
        if($('#disable_param').is(':checked') == true){
             $('#slider_item_12').slider( "option", "disabled", true );
             $('#slider_item_12').next().next().attr('readonly', true);
             $('#slider_item_13').slider( "option", "disabled", true );
             $('#slider_item_13').next().next().attr('readonly', true);
             $('#slider_item_14').slider( "option", "disabled", true );
             $('#slider_item_14').next().next().attr('readonly', true);
             $('#slider_item_15').slider( "option", "disabled", true );
             $('#slider_item_15').next().next().attr('readonly', true);
        }
        $.ajax({
            url: "<?=$this->url(array(),'site-ajax')?>",
            method: 'POST',
            data: $('#forms').serialize(),
            beforeSend: function( xhr ) {
                $('#block').show();
            }
        }).done(function(data ) {
            $('#block').hide();
            var html = '';
            var z = 0;
            for(x in data){
                if(x == 1){
                    txt = '<?=$this->translate('SITE_GLASS_1')?>';
                }
                if(x == 2){
                    txt = '<?=$this->translate('SITE_GLASS_2')?>';
                }
                if(x == 3){
                    txt = '<?=$this->translate('SITE_GLASS_3')?>';
                }
                html += '<h3 style="margin-bottom: 2px; font-size:16px; padding-bottom:0px;">' + txt+ '</h3>';
                html += '<ul style="margin-top: 4px;">';
                for(d in data[x]){
                    z++;
                    html += '<li>' + data[x][d].name + '</li>';
                }
                html += '</ul>';
            }
            $('#resuls').html(html)
        });
    });
    $.ajax({
        url: "<?=$this->url(array(),'site-ajax')?>",
        method: 'POST',
        data: $('#forms').serialize()
    }).done(function(data ) {
        var html = '';
        var z = 0;
        for(x in data){
            if(x == 1){
                txt = '<?=$this->translate('SITE_GLASS_1')?>';
            }
            if(x == 2){
                txt = '<?=$this->translate('SITE_GLASS_2')?>';
            }
            if(x == 3){
                txt = '<?=$this->translate('SITE_GLASS_3')?>';
            }
            html += '<h3 style="margin-bottom: 2px; font-size:16px; padding-bottom:0px;">' + txt+ '</h3>';
            html += '<ul style="margin-top: 4px;">';
            for(d in data[x]){
                z++;
                html += '<li>' + data[x][d].name + '</li>';
            }
            html += '</ul>';
        }
        $('#resuls').html(html);
    });
});
</script>