<?php
$special22 = array(40, 41, 38, 43, 44, 45);
$special223 = array(40, 41);
?>
<form id="forms" style="padding-top: 20px;" action="<?= $this->url(array('lang' => $this->lang), 'site-pdf') ?>" method="POST">
    <input type="hidden" name="show_in_us" value="<?= $this->show_in_us; ?>">
    <?php
    $i = 1;
    foreach ($this->group as $group_name => $sliders):
        ?>
        <?php $notshow = false; ?>
        <?php $array_keys = array_keys($sliders); ?>
        <?php $elem = ($sliders[array_shift($array_keys)]->toArray()); ?>
        <?php $ck = ''; ?>
        <?php $ck .= ($i != 1 && $elem['can_hide'] == 1) ? 'hide tercja' : ''; ?>
        <?php $ck .= ($i != 1) ? ' disabled hide' : ''; ?>
        <div class="element element-<?=$group_name?>  <?= ($elem['css_class']) ? $elem['css_class'] : $ck; ?>">
            <?php if ($elem['css_class'] == 'protection_class special22'): ?>
                <?php $notshow = true; ?>
                <?php $size = 432; ?>
                <p style="display: block;overflow: hidden; margin-bottom: 5px">
                    <a id="button4"  class="<?= $elem['css_class'] ?> up4" href="#" >
                        <img src="<?= $this->imagePath('ok.png') ?>"/>
                        <span><?= $this->translate('SITE_SECTION_PROTECTION_CLASS') ?></span>
                    </a>
                </p>
            <?php endif; ?>
            <?php if ($elem['css_class'] == 'size special22'): ?>
                <?php $notshow = true; ?>
                <?php $size = 432; ?>
                <p style="display: block;overflow: hidden; margin-bottom: 5px">
                    <a id="button1"  class="up4 <?= $elem['css_class'] ?>" href="#" >
                        <img src="<?= $this->imagePath('gs.png') ?>"/>
                        <span><?= $this->translate('SITE_SECTION_TOTAL_WIDTH') ?></span>
                    </a>
                </p>
            <?php endif; ?>
            <?php if ($elem['css_class'] == 'glass_laminate'): ?>
                <?php $notshow = true; ?>
                <?php $size = 432; ?>
                <p style="display: block;overflow: hidden; margin-bottom: 5px">
                    <a id="button6"  class="up4" href="#" >
                        <img id="ll" style="display:none;" src="<?= $this->imagePath('locked.jpg') ?>"/>
                        <img id="ul" src="<?= $this->imagePath('unlocked.jpg') ?>"/>
                        <span><?= $this->translate('SITE_SECTION_LAMINATED_GLASS') ?></span>
                    </a>
                </p>
            <?php endif; ?>
            <?php if ($elem['css_class'] == 'safety special22'): ?>
                <?php $notshow = true; ?>
                <?php $size = 432; ?>
                <p style="display: block;overflow: hidden; margin-bottom: 5px">
                    <a id="button2"  class="up4 <?= $elem['css_class'] ?>" href="#" style=" float:left; " >
                        <img src="<?= $this->imagePath('okb.png') ?>"/>
                        <span><?= $this->translate('SITE_SECTION_SECURITY_CLASS') ?></span>
                    </a>
                </p>
            <?php endif; ?>
            <?php if ($elem['css_class'] == 'weight special22'): ?>
                <?php $notshow = true; ?>
                <?php $size = 432; ?>
                <p style="display: block;overflow: hidden; margin-bottom: 5px">
                    <a id="button3"  class="up4 <?= $elem['css_class'] ?>" href="#" style=" float:left; " >
                        <?
						if ($this->lang=="en_US") {
						?>
							<img src="<?= $this->imagePath('lb.png') ?>"/>
						<?
						} else {
						?>
							<img src="<?= $this->imagePath('kg.png') ?>"/>						
						<?
						}
						?>
                        <span><?= $this->translate('SITE_SECTION_WEIGHT') ?></span>
                    </a>
                </p>
            <?php endif; ?>
            <?php if ($elem['css_class'] == 'glass_size special22'): ?>
                <?php $notshow = true; ?>
                <?php $size = 120; ?>
                <p style="display: block;overflow: hidden; margin-bottom:5px">

                    <a id="button2"  class="up4 <?= $elem['css_class'] ?>" href="#" style=" float:left;" >
                        <img src="<?= $this->imagePath('og.png') ?>"/>
                        <span><?= $this->translate('SITE_SECTION_GLASES_WIDTH') ?></span>
                    </a>
                </p>
                <p class="item" style="width: 100%; height: auto; margin-bottom: 10px;">
                    <span style="color: #003968; font-size: 16px; margin-bottom: 5px; height: 27px; text-transform: uppercase;"><?= $this->translate('SITE_TITLE_GLASES_WIDTH') ?></span>
                    <?/*= $this->translate('SITE_ANASTOMOSIS_TYPE') */?>
                    <select id="glass_size_options" style="visibility: hidden">
                        <option value="0"><?= $this->translate('SITE_ANASTOMOSIS_TYPE_0') ?></option>
                        <option value="1"><?= $this->translate('SITE_ANASTOMOSIS_TYPE_1') ?></option>
                        <option value="2"><?= $this->translate('SITE_ANASTOMOSIS_TYPE_2') ?></option>
                        <option value="3"><?= $this->translate('SITE_ANASTOMOSIS_TYPE_3') ?></option>
                    </select>
                </p>
            <?php endif; ?>
            <?Php $right = (532 / (count($sliders) + 1) - 50); ?>
            <?php if ($i == 1 || in_array($i, array(5, 6, 7, 8, 9, 10))) { ?>
                <div class="item" style='margin-right: <?= $right ?>px; position:relative;'>
                    <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px; height: 27px; width: 45px; padding-top: 75px;"><?= $this->translate('SITE_MAX') ?></p>
                    <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px; height: 27px; width: 45px; position: absolute;bottom: 0px;"><?= $this->translate('SITE_MIN') ?></p>
                </div>
            <?php } else { ?>
                <div class="item" style='margin-right: <?= $right ?>px; position:relative;'>
                    <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px; height: 27px;"><?= $elem['group_name'] ?></p>
                    <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px; height: 27px; position: absolute;bottom: 0px;left: 14px;"><?= $elem['hint'] ?></p>
                </div>
                <?php if ($notshow != FALSE): ?>
                    <?php $right = $size; ?>
                <?php endif; ?>
            <?php } ?>

            <?php foreach ($sliders as $value): ?>
				
				<?
				/**
				 * Dla wersji amerykańskiej pomijamy atrybuty Rw, C, Ctr, Ra, Ratr
				 */
				if ($value->id!=10 && $value->id!=12 && $value->id!=13 && $value->id!=14 && $value->id!=15) {
					
                switch ($value->id) {
                    case 10:
                        $item_prefix = 'Rw';
                        break;
                    case 12:
                        $item_prefix = 'C';
                        break;
                    case 13:
                        $item_prefix = 'Ctr';
                        break;
                    case 14:
                        $item_prefix = 'Ra';
                        break;
                    case 15:
                        $item_prefix = 'Ratr';
                        break;
                    default :
                        $item_prefix = '';
                        break;
                }

                if (!empty($item_prefix)) {
                    ?>

                    <script type="text/javascript">

                        var <?= $item_prefix ?> = 'item_<?= $value->id ?>';
                        var <?= $item_prefix ?>_min = <?= $value->min_value ?>;
                        var <?= $item_prefix ?>_max = <?= $value->max_value ?>;

                    </script>


                    <?php
                }

                //slider - typ 1  
				/**
				 * Przyciski dolne
				 */
                if ($value->id == 10 || $value->id == 14 || $value->id == 15 || $value->id == 42 || $value->id == 46  || in_array($value->id, $special22)) {	
				?>
                    <div class="item group-<?=$value->group_id?>" id="item_<?= $value->id ?>" style='margin-right: <?= $right ?>px;'>
                        <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; ">
                            <?php if ($value->id == 38): ?>
                                <?= $this->translate('SITE_TITLE_TOTAL_WIDTH') ?>
                            <?php elseif ($value->id == 42): ?>
                                <?= $this->translate('SITE_TITLE_WEIGHT') ?>
                            <?php elseif ($value->id == 40): ?>
                                <?= $this->translate('SITE_TITLE_PROTECTION_CLASS') ?>
                            <?php elseif ($value->id == 41): ?>
                                <?= $this->translate('SITE_TITLE_SECURITY_CLASS') ?>
							<?php else: ?>
								<?php echo $value->name; ?>
                            <?php endif; ?>
                        </p>
                        <?php if ($i == 1) { ?>
                            <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; "><?= $this->translate('SITE_UNIT_DB') ?></p>
                        <?php } ?>

                        <?php if ($elem['css_class'] == 'glass_size special22'): ?>
                            <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; "><?= $this->translate('SITE_UNIT_MM') ?></p>
                        <?php endif; ?>

                        <?php if ($elem['css_class'] == 'protection_class special22'): ?>
                            <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; "><?= $this->translate('SITE_UNIT_CLASS') ?></p>
                        <?php endif; ?>

                        <?php if ($elem['css_class'] == 'size special22'): ?>
                            <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; "><?= $this->translate('SITE_UNIT_MM') ?></p>
                        <?php endif; ?>

                        <?php if ($elem['css_class'] == 'weight special22'): ?>
                            <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; "><?= $this->translate('SITE_UNIT_KG') ?></p>
                        <?php endif; ?>

                        <?php if ($elem['css_class'] == 'safety special22'): ?>
                            <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; "><?= $this->translate('SITE_UNIT_CLASS') ?></p>
                        <?php endif; ?>

                        <?php if (in_array($value->id, $special223)): ?>
                            <p style="height: 50px; width: 43px; display: block;">
                                <input value="<?= @$this->values[$value->id][$value->max_value] ?>" readonly type="text" class="slider_amount first" />
                            </p>
                        <?php endif; ?>
                        <p style="height: 50px; width: 43px; display: block; <?= (in_array($value->id, $special223)) ? 'display:none;' : '' ?>">
							
							<?
							/**
							 * Przeliczenie wagi w KB na LB dla wersji amerykanskiej.
							 */
							if ($this->lang=="en_US" && $value->group_id==34) {
								$max_item_value2=ceil($value->max_value/0.45359237);
							} else {								
								$max_item_value2=$value->max_value;
							}
							?>							
							
                            <input name="<?= $value->id ?>[max]" type="text" value="<?= preg_replace(array('/\.00/', '/\.0/'), '', $max_item_value2) ?>" class="slider_amount first hidden" />
                        </p>
                        <a class="up_f" href="#"><img class="img_arrow_up" src="<?= $this->imagePath('arrow_up.png') ?>" /></a>
                        <a class="down_f" href="#"><img class="img_arrow_down" src="<?= $this->imagePath('arrow_down.png') ?>" /></a>
                        <div id="slider_item_<?= $value->id ?>" class="slider-vertical" style="height:200px;"></div>
                        <a class="up_l" href="#"><img class="img_arrow_up" src="<?= $this->imagePath('arrow_up.png') ?>" /></a>
                        <a class="down_l" href="#"><img class="img_arrow_down"  src="<?= $this->imagePath('arrow_down.png') ?>" /></a>
                        <?php if (in_array($value->id, $special223)): ?>
                            <p style="height: 50px; width: 43px; display: block;">
                                <input value="<?php if(in_array($this->values[$value->id][$value->min_value], array('BRAK', 'Brak', 'brak'))){
                                        echo $this->translate('SITE_EMPTY');
                                    }else{
                                        echo $this->values[$value->id][$value->min_value];
                                    }?>" readonly  type="text" class="slider_amount last" />
                            </p>
                        <?php endif; ?>

                        <p style="height: 50px; width: 43px; display: block; <?= (in_array($value->id, $special223)) ? 'display:none;' : '' ?>">
							
							<?
							/**
							 * Przeliczenie wagi w KB na LB dla wersji amerykanskiej.
							 */
							if ($this->lang=="en_US" && $value->group_id==34) {
								$min_item_value2=ceil($value->min_value/0.45359237);
							} else {								
								$min_item_value2=$value->min_value;
							}
							?>
							
                            <input name="<?= $value->id ?>[min]" type="text" value="<?= preg_replace(array('/\.00/', '/\.0/'), '', $min_item_value2) ?>" class="slider_amount last hidden" />
                        </p>
                    </div>


                    <script type="text/javascript">
                        $("#slider_item_<?= $value->id ?>").slider({
                            orientation: "vertical",
                            min: parseFloat('<?= preg_replace('/,/', '.', $min_item_value2) ?>'),
                            max: parseFloat('<?= preg_replace('/,/', '.', $max_item_value2) ?>'),
                            step: parseFloat('<?= preg_replace('/,/', '.', $value->step) ?>'),
                            range: true,
                            values: [<?= $min_item_value2 ?>, <?= $max_item_value2 ?>],
                            slide: function(event, ui) {
                                $(ui.handle).parent().parent().find('.first').val(ui.values[1]);
                                $(ui.handle).parent().parent().find('.last').val(ui.values[0]);
                                changeValues(this);
                            },
                            change: function(event, ui) {

                                step = parseFloat($("#slider_item_<?= $value->id ?>").slider("option", "step"));
                                max = parseFloat($("#slider_item_<?= $value->id ?>").slider("option", "max"));
                                min = parseFloat($("#slider_item_<?= $value->id ?>").slider("option", "min"));

                                if ((max == ui.values[1] && ui.values[0] == ui.values[1])) {
                                    if (max <= ui.values[1]) {

                                        $(ui.handle).parent().parent().find('.last').val(max);
                                    } else {
                                        $(ui.handle).parent().parent().find('.last').val(ui.values[1] - step);
                                        $(this).parent().find('.slider-vertical').slider("option", "values", [ui.values[1] - step, ui.values[0]]);
                                    }
                                } else {
                                    $(ui.handle).parent().parent().find('.last').val(ui.values[0]);
                                }
                                if ((min == ui.values[0] && ui.values[0] == ui.values[1])) {
                                    if (min >= ui.values[1]) {
                                        $(ui.handle).parent().parent().find('.first').val(min);
                                    }
                                } else {
                                    $(ui.handle).parent().parent().find('.first').val(ui.values[1]);
                                }

                                if (semafor == 0) {
                                    handle_change('<?= $item_prefix ?>');
                                    postAjax();
                                }
                                changeValues(this);

                            }
                        });
                    </script>

                    <?php
                } else {
                    ?>					
					<!--SUWAKI GŁÓWNE-->
                    <div class="item item2 group-<?=$value->group_id?>" id="item_<?=$value->id ?>" style='margin-right: <?= $right ?>px;'>
						
						<?php
						/**
						 * Dla amerykańskiej wersji zaokraglamy wartości
						 * tercji i oktaw
						 */							
						$max_item_value=ceil($value->max_value);
						?>						
						
                        <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; "><?= $value->name ?></p>
                        <?php if ($i == 1) { ?>
                            <p style="font-size: 18px; text-align: center; display: block; margin-bottom: 5px;height: 27px; ">[dB]</p>

                        <?php } ?>
                        <p style="height: 50px; width: 43px; display: block;">
                            <input name="<?= $value->id ?>[max]" type="text" value="<?= preg_replace(array('/\.00/', '/\.0/'), '', $max_item_value) ?>" class="item_max_indicator" />
                        </p>

                        <a class="up" href="#"><img class="img_arrow_up" src="<?= $this->imagePath('arrow_up.png') ?>" /></a>
                        <div id="slider_item_<?= $value->id ?>" class="slider-vertical" style="height:200px;"></div>
                        <a class="down" href="#"><img class="img_arrow_down"  src="<?= $this->imagePath('arrow_down.png') ?>" /></a>
						
						<?php
						/**
						 * Dla amerykańskiej wersji zaokraglamy wartości
						 * tercji i oktaw
						 */						
						if ($this->lang=="en_US" && ($value->group_id==25 || $value->group_id==28 || $value->group_id==26)) {
							
							//echo $value->group_id;
							//echo "<br />";
							//echo $value->id;
							
							$min_item_value=round($value->min_value);
							
							
							//echo $value->min_value.'--'.$min_item_value.'--'.$value->step;
							
							$step=1;
							
							//$min_item_value=$value->min_value;
							//$step=preg_replace('/,/', '.', $value->step);							
							
						} else {
							$min_item_value=$value->min_value;
							$step=preg_replace('/,/', '.', $value->step);
						}
						?>
						
                        <input name="<?= $value->id ?>" type="text" value="<?=$min_item_value?>" class="slider_amount" />
                    </div>
                    <script>
                        $(function() {
                            $("#slider_item_<?= $value->id ?>").slider({
                                orientation: "vertical",
                                range: "min",
                                min: parseInt('<?= (empty($min_item_value) || !in_array($value->id, array('10', '12', '13'))) ? $min_item_value : $min_item_value ?>'),
                                max: parseInt('<?= (empty($max_item_value) || !in_array($value->id, array('10', '12', '13'))) ? $max_item_value : $max_item_value ?>'),
                                step: parseFloat('<?=$step ?>'),
                                value: parseInt('<?= $min_item_value ?>'),
                                slide: function(event, ui) {
                                   //alert(ui.value);
                                    $(ui.handle).parent().parent().find('.slider_amount').val( ui.value );

                                },
                                change: function(event, ui) {

                                    $(ui.handle).parent().parent().find('.slider_amount').val(ui.value);
                                    if (semafor == 0) {
                                        handle_change('<?= $item_prefix ?>');
                                        postAjax();
                                    }
                                }
                            });
                        });
                    </script>
					<!--END SUWAKI GŁÓWNE-->
					
                    <?php
            }					
					
					//koniec
				}
				?>
				
				

			<?
            endforeach;
            ?>
            <?php if ($i == 1 && count($this->group) > 1): ?>
                <div style="clear: both; width: 100%;">
                    <br />
                    <a id="lock_button"  class="btn-slider" href="#" style="clear: both; float:left; padding: 3px 5px 3px 3px;" ><img class="img_arrow_down"  src="<?= $this->imagePath('locked.png') ?>" /></a>
                    <div style="float:left; padding:2px 0px 0px 10px; width: 450px;"><?= $this->translate('SITE_DEPENDENCY_BUTTON') ?></div>
                    <br />
                </div>
                <div style="clear: both; width: 100%;">
                    <a id="terc_button"  class="btn-slider" href="#" style="float:right; margin-top: 30px; display: none;"><?= $this->translate('SITE_TERC_ON') ?></a>
                    <a id="oktawy_button"  class="btn-slider" href="#" style=" float:left; margin-top: 30px; "><?= $this->translate('SITE_OKTAWY_ON') ?></a>
                </div>
            <?php endif; ?>
            <?php if ($elem['css_class'] == 'glass_size special22'): ?>
                <div class="legend">
                    <ul style="list-style:none;">
                        <li>
                            <img style="position: relative; top: 4px;" src="<?= $this->imagePath('x.jpg') ?>"/>
                            <?= $this->translate('SITE_THICKNESS_LEGEND_1') ?>
                        </li>
                        <li>
                            <img style="position: relative; top: 4px;" src="<?= $this->imagePath('y.jpg') ?>"/>
                            <?= $this->translate('SITE_THICKNESS_LEGEND_2') ?>
                        </li>
                        <li>
                            <img style="position: relative; top: 4px;" src="<?= $this->imagePath('z.jpg') ?>"/>
                            <?= $this->translate('SITE_THICKNESS_LEGEND_3') ?>
                        </li>
                    </ul>
                </div>
            <?php endif; ?>
        </div>
        <?php
        $i++;
    endforeach;
    ?>
    <input class="btn-slider" id="submit_print" type="submit" value="<?= $this->translate('SITE_SAVE') ?>" />
</form>
<script>
    $(document).ready(function() {
        var item = $('.item');


        item.each(function() {
            var top = $(this).find('.slider_amount.first');
            var bottom = $(this).find('.slider_amount.last');
            var slider = $(this).find('.slider-vertical');
            var itemattr = $(this).attr('id');

            if (itemattr !== "item_40" && itemattr !== "item_41") {
//                console.warn(itemattr);

                top.change(function() {
                    var value = parseInt($(this).val());
                    $(this).closest('div').find('.slider-vertical').slider("values", 1, value);
                });
                bottom.change(function() {
                    var value = parseInt($(this).val());
                    $(this).closest('div').find('.slider-vertical').slider("values", 0, value);
                });
            }
        });
    });
    //Rw: id = 10
    //C: id = 12
    //Ctr: id = 13
    //RA: id = 14
    //RAtr: id = 15
    var current_mode = '1';
    var semafor = 0; //do kontroli kto odpalił zmianę wartości
    var is_locked = true;  //wzajemna zależność suwaków


    function changeValues(slider)
    {
        var slider_id = ($(slider).attr('id').replace('slider_item_', ''));
        var values = eval('(' + '<?= json_encode($this->values) ?>' + ')');
        if (values[slider_id] !== undefined) {
            $(slider).parent().parent().find('.last').not('.hidden').val(values[slider_id][$(slider).parent().parent().find('.last').val()])
            $(slider).parent().parent().find('.first').not('.hidden').val(values[slider_id][$(slider).parent().parent().find('.first').val()])
        }
    }

    function set_dependency_lock(lock) {
        is_locked = lock;
        if (is_locked) {
            $('#lock_button img').attr('src', '<?= $this->imagePath('locked.png') ?>');
        }
        else {
            $('#lock_button img').attr('src', '<?= $this->imagePath('unlocked.png') ?>');
        }
    }

    function set_item_mode(item_id, disabled) {
        // alert($(item_id));
        $('#' + item_id + ' .slider-vertical').slider("option", "disabled", disabled);
        $('#' + item_id + ' input').attr('readonly', disabled);
        $('#' + item_id + ' input').attr('disabled', disabled);

        if (disabled) {
            $('#' + item_id + ' .img_arrow_up').attr('src', '<?= $this->imagePath('arrow_up_.png') ?>');
            $('#' + item_id + ' .img_arrow_down').attr('src', '<?= $this->imagePath('arrow_down_.png') ?>');
        }
        else {
            $('#' + item_id + ' .img_arrow_up').attr('src', '<?= $this->imagePath('arrow_up.png') ?>');
            $('#' + item_id + ' .img_arrow_down').attr('src', '<?= $this->imagePath('arrow_down.png') ?>');
        }

    }

    function set_item_values(item_id, min_value, min_scale, max_value, max_scale) {
        console.log(max_value);
        semafor = 1;
        if ($('#' + item_id).hasClass("item2")) {  //stary slider
            $('#' + item_id + ' .slider-vertical').slider("option", "min", min_scale);
            $('#' + item_id + ' .slider-vertical').slider("option", "max", max_scale);
            $('#' + item_id + ' .slider-vertical').slider("value", min_value);
            $('#' + item_id + ' input').not('.item_max_indicator').val(min_value);
        }
        else { //nowy slider
            $('#' + item_id + ' .slider-vertical').slider("option", "min", min_scale);
            $('#' + item_id + ' .slider-vertical').slider("option", "max", max_scale);
            $('#' + item_id + ' .slider-vertical').slider("values", [min_value, max_value]);
            $('#' + item_id + ' input .last').val(min_value);
            $('#' + item_id + ' input .first').val(max_value);
        }
        semafor = 0;
    }

    function get_item_values(item_id) {
        values = [0, 0];
        if ($('#' + item_id).hasClass("item2")) {  //stary slider
            values[0] = $('#' + item_id + ' .slider-vertical').slider("value");
        }
        else { //nowy slider
            values = $('#' + item_id + ' .slider-vertical').slider("values");
        }
        return values;
    }


    function handle_change(item_code) {

        
    }


    function calculate_dependencies(slider_id, min_value, max_value) {

        var res = [];
        res_10 = [0, 0];
        res[10] = res_10;
        res_12 = [0, 0];
        res[12] = res_12;
        res_13 = [0, 0];
        res[13] = res_13;
        res_14 = [0, 0];
        res[14] = res_14;
        res_15 = [0, 0];
        res[15] = res_15;

        for (index = 0; index < attributes.length; ++index) {
            slider_values = attributes[index];
            //sprawdz czy spełnia
            if (slider_values[slider_id] < min_value) {
                continue;
            }

            if (max_value != 0 && slider_values[slider_id] > max_value) {
                continue;
            }

            if (res[10][0] == 0) {
                res[10][0] = slider_values[10];
                res[10][1] = slider_values[10];
            }

            if (res[12][0] == 0) {
                res[12][0] = slider_values[12];
                res[12][1] = slider_values[12];
            }

            if (res[13][0] == 0) {
                res[13][0] = slider_values[13];
                res[13][1] = slider_values[13];
            }

            if (res[14][0] == 0) {
                res[14][0] = slider_values[14];
                res[14][1] = slider_values[14];
            }

            if (res[15][0] == 0) {
                res[15][0] = slider_values[15];
                res[15][1] = slider_values[15];
            }

            if (res[10][0] > slider_values[10])
                res[10][0] = slider_values[10];

            if (res[10][1] < slider_values[10])
                res[10][1] = slider_values[10];

            if (res[12][0] > slider_values[12])
                res[12][0] = slider_values[12];

            if (res[12][1] < slider_values[12])
                res[12][1] = slider_values[12];


            if (res[13][0] > slider_values[13])
                res[13][0] = slider_values[13];

            if (res[13][1] < slider_values[13])
                res[13][1] = slider_values[13];

            if (res[14][0] > slider_values[14])
                res[14][0] = slider_values[14];

            if (res[14][1] < slider_values[14])
                res[14][1] = slider_values[14];

            if (res[15][0] > slider_values[15])
                res[15][0] = slider_values[15];

            if (res[15][1] < slider_values[15])
                res[15][1] = slider_values[15];
        }

        return res;
    }

    //ustaw nowy tryb
    function set_mode(mode) {
        current_mode = mode;
        
		

        //upgade 4
        $('a.special22').parent().parent().find('.item').each(function() {
            if ($(this).is(':visible') == false) {
                if ($(this).attr('id') !== undefined) {
                    set_item_mode($(this).attr('id'), true);
                }
            }
        });

		/**
		 * Odczekaj chwilę.
		 */
		setTimeout(function(){
			postAjax();				
		},500);
    }

    $(function() {


        set_mode(current_mode); //domyślny tryb
        $('.disabled input').attr('disabled', true);

        $('#lock_button').click(function(e) {
            e.preventDefault();
            set_dependency_lock(!is_locked);
        });




        //nowy slider 
        $('.up_l').click(function(e) {
            e.preventDefault();

            if ($(this).parent().find('.slider-vertical').slider("option", "disabled") == true) {
                return false;
            }

            var values = ($(this).parent().find('.slider-vertical').slider("option", "values"));
            var max = ($(this).parent().find('.slider-vertical').slider("option", "max"))

            if (values[1] == values[0]) {
                return false;
            }

            if (max - values[0] <= -1) {
                return false;
            }
            var step = ($(this).parent().find('.slider-vertical').slider("option", "step"));
            $(this).parent().find('.slider-vertical').slider("values", 0, values[0] + step);
        });
        $('.down_l').click(function(e) {
            e.preventDefault();

            if ($(this).parent().find('.slider-vertical').slider("option", "disabled") == true) {
                return false;
            }

            var values = ($(this).parent().find('.slider-vertical').slider("option", "values"));
            var min = ($(this).parent().find('.slider-vertical').slider("option", "min"))
            if (values[1] - min <= 1) {
                return false;
            }
            var step = ($(this).parent().find('.slider-vertical').slider("option", "step"));
            $(this).parent().find('.slider-vertical').slider("values", 0, values[0] - step);
        });
        $('.up_f').click(function(e) {
            e.preventDefault();

            if ($(this).parent().find('.slider-vertical').slider("option", "disabled") == true) {
                return false;
            }

            var values = ($(this).parent().find('.slider-vertical').slider("option", "values"));
            var max = ($(this).parent().find('.slider-vertical').slider("option", "max"))
            if (max == values[1]) {
                return false;
            }
            var step = ($(this).parent().find('.slider-vertical').slider("option", "step"));
            $(this).parent().find('.slider-vertical').slider("values", 1, values[1] + step);
        });
        $('.down_f').click(function(e) {
            e.preventDefault();

            if ($(this).parent().find('.slider-vertical').slider("option", "disabled") == true) {
                return false;
            }

            var values = ($(this).parent().find('.slider-vertical').slider("option", "values"));
            var min = ($(this).parent().find('.slider-vertical').slider("option", "min"))

            if (values[1] == values[0]) {
                return false;
            }

            if (values[1] - min <= -1) {
                return false;
            }
            var step = ($(this).parent().find('.slider-vertical').slider("option", "step"));
            $(this).parent().find('.slider-vertical').slider("values", 1, values[1] - step);
        });


        $('.up').click(function(e) {
            e.preventDefault();
            var value = $(this).next().slider("value");
            if ($(this).next().slider("option", "disabled") == true) {
                return false;
            }
            $(this).next().slider("value", value + 1);
        });
		
		
		/**
		 * Kliknięcie w dół - slider
		 */
        $('.down').click(function(e) {
			
			
            e.preventDefault();
            var value = $(this).prev().slider("value");
            if ($(this).prev().slider("option", "disabled") == true) {
                return false;
            }
			
            $(this).prev().slider("value", value - 1);
			
			console.log(value);
			
			
        });
		/**
		 * END:
		 */



        $('#mode').change(function(e) {
            set_mode($('#mode').val());
        });












        $('#block').height($(document).height());

        $('#oktawy_button').click(function(e) {
            e.preventDefault();
            $('#terc_button').toggle();
            if ($('#oktawy_button').html() == '<?= $this->translate('SITE_OKTAWY_ON') ?>') {
                $('#oktawy_button').html('<?= $this->translate('SITE_OKTAWY_OFF') ?>');
                $('.hide').not('.tercja').show();
                if ($('#terc_button').html() == '<?= $this->translate('SITE_TERC_OFF') ?>') {
                    $('.tercja').show();
                    $('.element').addClass('bg');
                }
            }
            else {
                $('#oktawy_button').html('<?= $this->translate('SITE_OKTAWY_ON') ?>');
                $('.hide').hide();
                $('.element').removeClass('bg');
            }

            $('.disabled input').attr('disabled', true);
            $('.disabled:visible input').attr('disabled', false);
            postAjax();
        });


        $('#terc_button').click(function(e) {
            e.preventDefault();
            if ($('#terc_button').html() == '<?= $this->translate('SITE_TERC_ON') ?>') {
                $('#terc_button').html('<?= $this->translate('SITE_TERC_OFF') ?>');
            }
            else {
                $('#terc_button').html('<?= $this->translate('SITE_TERC_ON') ?>');
            }
            $('.tercja').toggle();
            $('.disabled').toggleClass('bg');

            $('.disabled input').attr('disabled', true);
            $('.disabled:visible input').attr('disabled', false);
            postAjax();
        });


        // BAND
        /* $('#disable_band').click(function(e){
         disabled = ($('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled"));
         if(disabled == false){
         $('.disabled').find('.slider_amount').attr('disabled', true);
         $('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled", true );
         } else {
         $('.disabled').find('.slider_amount').attr('disabled', false);
         $('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled", false );   
         }
         $('#slider_item_10').next().next().trigger('change');
         });
         
         disabled = ($('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled"));
         if(disabled == false){
         $('.disabled').find('.slider_amount').attr('disabled', true);
         $('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled", true );
         } else {
         $('.disabled').find('.slider_amount').attr('disabled', false);
         $('.disabled').find('.slider_amount').prev().prev().slider( "option", "disabled", false );   
         }
         
         */
        //END BAND






        $('.slider_amount').change(function() {
            val = $('input[name="options"]:checked').val();
            //tpysko: val
            //coment by kn
//            setValue($(this),$(this).val());
            if ($('#disable_rw').is(':checked') == true) {
                $('#slider_item_10').slider("option", "disabled", true);
                $('#slider_item_10').next().next().attr('readonly', true);
            }
            if (val == 2) {  //RA
                $('#slider_item_12').slider("option", "disabled", true);
                $('#slider_item_12').next().next().attr('readonly', true);
                $('#slider_item_13').slider("option", "disabled", true);
                $('#slider_item_13').next().next().attr('readonly', true);

                $('#slider_item_14').slider("option", "disabled", false);
                $('#slider_item_14').next().next().attr('readonly', false);
                $('#slider_item_15').slider("option", "disabled", false);
                $('#slider_item_15').next().next().attr('readonly', false);
            } else {  //C
                $('#slider_item_12').slider("option", "disabled", false);
                $('#slider_item_12').next().next().attr('readonly', false);
                $('#slider_item_13').slider("option", "disabled", false);
                $('#slider_item_13').next().next().attr('readonly', false);

                $('#slider_item_14').slider("option", "disabled", true);
                $('#slider_item_14').next().next().attr('readonly', true);
                $('#slider_item_15').slider("option", "disabled", true);
                $('#slider_item_15').next().next().attr('readonly', true);
            }
            if ($('#disable_param').is(':checked') == true) {
                $('#slider_item_12').slider("option", "disabled", true);
                $('#slider_item_12').next().next().attr('readonly', true);
                $('#slider_item_13').slider("option", "disabled", true);
                $('#slider_item_13').next().next().attr('readonly', true);
                $('#slider_item_14').slider("option", "disabled", true);
                $('#slider_item_14').next().next().attr('readonly', true);
                $('#slider_item_15').slider("option", "disabled", true);
                $('#slider_item_15').next().next().attr('readonly', true);
            }
            //tpysko
            //postAjax();
        });



    });




    /**
	* Wyszukiwarka - dane z formularza zwracane do f. ajax w PHP
	**/
    function postAjax() {
        $.ajax({
            url: "<?= $this->url(array('lang' => $this->lang), 'site-ajax') ?>",
            method: 'POST',
            data: $('#forms').serialize(),
            beforeSend: function(xhr) {
                $('#block').show();
            }
        }).done(function(data) {
			
			
			
            $('#block').hide();
            var html = '';
            var z = 0;
            for (x in data) {
                if (x == 1) {
                    txt = '<?= $this->translate('SITE_GLASS_1') ?>';
                }
                if (x == 2) {
                    txt = '<?= $this->translate('SITE_GLASS_2') ?>';
                }
                if (x == 3) {
                    txt = '<?= $this->translate('SITE_GLASS_3') ?>';
                }
                html += '<h3 style="margin-bottom: 2px; font-size:16px; padding-bottom:0px;">' + txt + '</h3>';
                html += '<ul style="margin-top: 4px;">';
                for (d in data[x]) {
                    z++;
                    html += '<li>' + data[x][d].name + '</li>';
                }
                html += '</ul>';
            }
            $('#resuls').html(html)
        });
    }
	/**
	* END
	* */

    var attributes = [];
<?php
$i = 0;
foreach ($this->attributes_realtion as $r_k => $r_v) {
    echo 'var a_' . $r_k . ' = [];
             ';
    foreach ($r_v as $a_k => $a_v) {
        echo 'a_' . $r_k . '[' . $a_k . '] = ' . $a_v . ';
             ';
    }
    echo 'attributes[' . $i . '] = a_' . $r_k . ';
             ';

    $i++;
}
?>

    $('a.special22').click(function(e) {
        e.stopPropagation();
        e.preventDefault();
        $(this).parent().parent().find('.item').each(function() {
            if ($(this).is(':visible') == true) {
                if ($(this).attr('id') !== undefined) {
                    set_item_mode($(this).attr('id'), true);
                }
            } else {
                if ($(this).attr('id') !== undefined) {
                    set_item_mode($(this).attr('id'), false);
                }
            }
        });
//        if($(this).parent().parent().hasClass('glass_size')){
//            $('#glass_size_options').change();
//        }
        postAjax();
        $(this).parent().parent().find('.item').toggle();
        $(this).parent().parent().find('.legend').toggle();
    });

    $('#button6').click(function(e) {
        e.stopPropagation();
        e.preventDefault();
        if ($('#ll').is(':visible')) {
            $('#ll').hide();
            $('#ul').show();
            $('#slider_item_39').next('a').click();
        } else {
            $('#ul').hide();
            $('#ll').show();
            $('#slider_item_39').prev('a').click();
        }
    });

    $('#glass_size_options').change(function() {
        var value = $(this).val();
        switch (parseInt(value)) {
            case 0:
            case 3:
                set_item_mode('item_43', false);
                set_item_mode('item_44', false);
                set_item_mode('item_45', false);
                break;
            case 1:
                set_item_mode('item_43', false);
                set_item_mode('item_44', true);
                set_item_mode('item_45', true);
                break;
            case 2:
                set_item_mode('item_43', false);
                set_item_mode('item_44', true);
                set_item_mode('item_45', false);
                break;
        }
    });
</script>