<div id="taf" style="border-bottom: 1px solid #DBDBDB; margin-bottom: 20px;">
    <nav class="navbar navbar-default navbar-static-top" style="overflow: hidden; clear: both;">
        <div class="navbar-collapse">
            <ul class="nav navbar-nav">
                <li >
                    <a href="<?=$this->url(array('id' => $this->attribute->id),'admin-attributes-edit')?>">Dane podstawowe</a>
                </li>
                <li class="active">
                    <a href="#">Definiuj warości</a>
                </li>
            </ul>
        </div>
    </nav>
</div>
<hgroup>
    <h2>
        Atrybut - Klasa bezpieczeństwa  - wartości    </h2>
</hgroup>
<?=$this->listview;?>
<script>
    $(function(){
        var html = $('#taf').clone();
        $('#taf').remove();
        $('.box').prepend(html);
    });
</script>